# Generated by Django 4.0.1 on 2022-02-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_userprofile_following_userfollowing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='no bio provided', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='no location provided', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_at',
            field=models.CharField(blank=True, default='No work at or school', max_length=200, null=True),
        ),
    ]
