# Generated by Django 4.0.1 on 2022-01-09 22:31

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_files_remove_post_tags_remove_post_title_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
