# Generated by Django 4.0.1 on 2022-01-09 23:27

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
