# Generated by Django 4.0.1 on 2022-01-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
