# Generated by Django 4.0.1 on 2022-01-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_at',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
