# Generated by Django 4.0.1 on 2022-01-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_userprofile_work_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
    ]
