# Generated by Django 4.0.1 on 2022-01-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0025_userprofile_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='followers',
            new_name='following',
        ),
    ]
